### PR TITLE
Fix #5

### LINKED ISSUE #5: Heading semantics
### Issue
Visual headings are not marked up as heading elements. This disadvantages assistive technology and being able to navigate easily though content.

image

image

### Recommendations

```
<div class="card-content">
            <h2 class="card-title">Gerry McGovern blog</h2> <!-- visual heading is now marked up as a heading --> 
            <p class="card-authors"><strong>By:</strong> Gerry McGovern</p>
            <p class="card-publication"></p>
            <p class="card-desc">Gerry writes about the huge, and mostly hidden, environmental impact of all things digital. He looks at things that can be done to improve the...</p>
          </div>
```

[Techniques for addressing](https://www.w3.org/WAI/WCAG21/Techniques/html/H42)

### PR DESCRIPTION
**Pull request by ksyro98**
Fixing issue #5 by changing `p` tag to `h2` tag in cards.

### CODE REVIEW

**Comment by melissaegg** [comment]
OK I think I merged this! I get nervous about breaking things and have to reassure myself that I can always revert. thank you both for your help. I hope your holidays allow for deep rest and joy this year!

**Comment by ksyro98** [comment]
@melissaegg yep you did!
I'm testing changes locally before I create a PR, so they shouldn't break anything. And yes, we can always revert. :)

There's one more open issue (#3), I'll create a PR in the upcoming days.

**Comment by melissaegg** [comment]
No rush, I am so slow! Thanks for telling me that you are testing ahead of
time (maybe all devs do that I don't know!), that makes me feel better
about hitting merge! :)

*Melissa Eggleston*
*she/her/hers*
UX Designer & Instructor
704-280-9080
***@***.***

Want to become (more) trauma-informed?
Visit the Trauma-Informed Technology <https://www.traumainformedtech.com/>
website.

**Comment by ksyro98** [comment]
@melissaegg nah, you're not that slow. But also, we need some more slowness in tech, so please be slow. :)

(All developers test, some more some less, but the changes we're making are fairly simple and specific, so they don't need too much testing.)

**Pull request merged**
